- hosts: all
  become: yes
  vars:
    app_port: 8080
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Start Docker Compose
      shell: |
        cd /home/ubuntu
        docker-compose up -d
