- hosts: all
  become: yes
  vars:
    app_port: 8080
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
      changed_when: false

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Build Application Image
      docker_image:
        build:
        context: "{{ playbook }}/app"
        name: app
        tag: latest

    - name: Run Container
      docker_container:
        name: app
        image: app:latest
